#!/bin/sh

path=/sys/class/backlight/acpi_video0

luminance() {
	read -r level < "$path"/actual_brightness
		factor=$((100 / max))
		printf '%d\n' "$((level * factor))"
}

read -r max < "$path"/max_brightness

xbacklight -set "$(luminance)"

inotifywait -me modify --format '' "$path"/actual_brightness | while read; do
xbacklight -set "$(luminance)"
done
